[build]
  command = "npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-server.com/api/:splat"  # Replace with your actual backend URL
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
